### ISSUE TITLE
Initial API thoughts

### ISSUE THREAD

**Issue by johnstevenson** [composer/pcre#2]
This is going to be a very useful library. And because it's in the Composer family it will likely become huge and invoke all sorts of feaure requests.

In my view it primarily needs to be a drop-in replacement to make existing code safe. Using some Composer examples we can see how painless this could be:

```php
<?php
    if (preg_match($pattern, $line)) { ... }
    if (Regex::match($pattern, $line, $unused)) { ... }

    if (preg_match_all('{'.self::$DEFINES.'"'.$keyRegex.'"\s*:\s*(?:(?&json))}x', $children, $matches)) { ... }
    if (Regex::matchAll('{'.self::$DEFINES.'"'.$keyRegex.'"\s*:\s*(?:(?&json))}x', $children, $matches)) { ... }

    $childrenClean = preg_replace('{,\s*'.preg_quote($bestMatch).'}i', '', $children, -1, $count);
    $childrenClean = Regex::replace('{,\s*'.preg_quote($bestMatch).'}i', '', $children, -1, $count);
```

We can cover everyone's needs with `Regex::filter`, `Regex::grep`, `Regex::match`, `Regex::matchAll`, `Regex::replace`, `Regex::replaceCallback` and `Regex::replaceCallbackArray` in not much code that wraps the native PHP functions and throws a nice `PcreException` on regex errors, without emitting any warnings. The only downside for users would be having to add the optional params if they are not being used.

The decorator methods that return result objects could be simply named by appending `Ex`:

```php
<?php
$result = Regex::matchEx('{fo+}', $string);
if ($result->matched) { something($result->matches); }
```

What do you think? (I can PR any of this you like, if you don't have the time).

**Comment by johnstevenson** [comment]
Okay, I see that you want to keep the warnings, so that means `preg_filter` cannot be reliably handled (it can return an empty array on an error), so maybe we should just concentrate on the core `match`, `matchAll`, `replace` and `replaceCallback` for now.

 I'm curious why you've restricted `PREG_OFFSET_CAPTURE` in matches and array subjects in replaces. `Match...Result::matches` is an array regardless, and `ReplaceResult::result` _could_ be `string|array`.

**Comment by Seldaek** [comment]
> In my view it primarily needs to be a drop-in replacement to make existing code safe. 

Yes I agree the forcing of Result object kinda made me uneasy too. Too verbose :) Maybe what we could do instead of Regex::matchEx (in which I frankly have no clue what Ex is supposed to mean) is have a `Preg::match` following the `preg_*` API and `Regex::match` would wrap it in a result object as it does now. That means you use the class with the API that suits the verbosity needs, and no weird function naming ensues.

> Okay, I see that you want to keep the warnings, so that means preg_filter cannot be reliably handled (it can return an empty array on an error)

IMO we could also register an error handler every time to catch the warnings, I just didn't do it because Composer already registers one, and I expect anyone caring about warnings to also just turn them into exceptions already. I see the preg_filter limitation.. maybe we can just do the error handler for that one?

> I'm curious why you've restricted PREG_OFFSET_CAPTURE in matches and array subjects in replaces. Match...Result::matches is an array regardless, and ReplaceResult::result could be string|array.

That's exactly why I restricted it, I want to avoid union types as much as possible as it forces you to if() types away to get decent PHPStan type info, as it won't be able to infer the return type based on the flag's presence. 

The other reason is I saw it was not used anywhere in Composer itself. If we do need it we can add a matchCaptureOffset method or so with a different return type I'd say.

Any other feedback item I forgot to address?

**Comment by johnstevenson** [comment]
> Maybe what we could do instead of Regex::matchEx (in which I frankly have no clue what Ex is supposed to mean) is have a Preg::match following the preg_* API and Regex::match would wrap it in a result object as it does now. 

Yes, I'm rubbish at names (it's actually an MS thing, meaning Extended, but that doesn't make it any better). I see you've started the implementation of the separate `Preg` and `Regex` classes, which is a great idea and proves you're much better at naming things!

> I see the preg_filter limitation.. maybe we can just do the error handler for that one?

Sounds like the simplest solution.

> I want to avoid union types as much as possible as it forces you to if() types away to get decent PHPStan type info

Except some preg_ functions make full use of them. It's probably easier to demonstrate how this could work: https://github.com/composer/pcre/pull/3

**Comment by Seldaek** [comment]
Closing here. I'd say try implementing it in xdebug-handler and if it looks good I'll tag a 1.0.0

**Comment by Danon** [comment]
@Seldaek FYI you should be really careful with using warning handler to detect errors with pcre. Double check the corner cases and situations where you might call two different preg methods one after another and, for example when calling preg_match from within preg_replace_callback.

I tried to make it work good with warning handler and it didn't work. So make sure you double check them and write good unit tests for them.

**Comment by Danon** [comment]
Al so remember that different PHP versions return different types of warnings (sometimes error sometimes regular warning) and with different messages too.

**Comment by Seldaek** [comment]
We are not using an error handler, just detecting error return value after every call, so I think that simplifies things greatly.
