### ISSUE TITLE
Cool project, but why not use T-Regx?

### ISSUE THREAD

**Issue by Danon** [composer/pcre#5]
I appreciate your idea of type safe regular expressions, but what you created already exists:

https://t-regx.com/docs/introduction-safe

**Comment by Seldaek** [comment]
I did search for a solution before starting this, and found t-regx and spatie/regex. 

- spatie/regex is not workable for Composer right now due to the PHP version required, plus some minor API decisions which make it harder to work with than I'd like.
- t-regx looks good if you're into fluent APIs (although I now see you also support `preg::match` style API, I did not see this at first). But right now we anyway need PHP 5.3 support so it's a no go for me. I'd also suggest you release a 1.0 as this 0.x does not inspire much confidence IMO for a dependency of project like Composer at least :) I see you're reaching that milestone though so I added a reference in the README here, hopefully that directs any interested party the right way.

**Comment by Danon** [comment]
@Seldaek You know, actually we did support PHP 5.3 in T-Regx before, but we dropped it, because we didn't see anyone use that version. However, there are two sides to compatibility.

And there is no `1.0` release because the higher-level API still undergoes some changes, however the lower level API is actually stable, there will be no changes to it, since its supposed to be 1:1 PHP API. 

If the lower level API of T-Regx was released as 1.0, and to did support PHP 5.3-8.1, would you find it suitable? The higher level API will probably take months to a year for a release. 

First there's API compatibility (you can run the lib on PHP 5.3 if it uses new syntax).

Second, there's the functional compatibility - something works on PHP 5.3 but not on 7+ and vice versa.

In T-Regx we dropped only the first kind , because of the Type hints (in the higher-level API). The lower level API (the `preg::` wrappers actually would work perfectly on PHP 5.3 if I just delete the type hints.

I actually had a plan of splitting the SafeRegex part (`preg::` wrappers) and CleanRegex part (`pattern()`) into two separate packages. I see No reason that the lower level couldn't support PHP5.3 :)

**Comment by Seldaek** [comment]
I haven't looked at the low level API in details to know if it'd be fitting, frankly now that I got this here and it works I am not super inclined to use another moving target which is not under my control instead of something I can fix if needed.

I know it's not what you want to hear, but Composer does have slightly special needs in terms of dependencies, because it's a special project due to the way it sometimes runs with a mix of project dependencies loaded in process too, plus the security requirements. We are very careful and conservative about adding new dependencies on third parties.

So I'd say don't waste time on us here, and don't waste time supporting 5.3, this is an insane requirement in 2021 that I don't wish on anyone else ;)

**Comment by Danon** [comment]
Oh, I know exactly what you mean! I too was sqrewed over by a library maintainer in the past. I understand perfectly that any library comes with a cost and a price, even though it's free. The cost of coupling your project to someone elses can often greatly exceed the benefits of the library. I'm with you on that. I also understand that often we love something when we made it.

But also, I noticed we value similar ideas. Type safety, exceptions over magic values, we don't like `false` and `null` as markers, and we both appreciate good tests. We also both agree that PHP PCRE is crap.

Please, don't think I'm trying to sell you the library if you don't want it, I simply think we share similar goals and might help each other. I worked on PHP regular epxresions for over 7 years now, (including PHP C code for PCRE) I know them in and out. Perhaps I can share some of my work with those who need it.

But I understand your decision, do as you find best for your project. Best of luck! :) 

Out of curiosity, what issues did you speak of before? Excuse me, I'm just cuirous. I've put a lot of thoughts to designing it, and I was under the imoresion it would suit everybody. Could you give me some advice as to why exactly did you decide not to go with it? You mentioned project and security requirements? It would help me make it better, if not for you, at least for others?

**Comment by Seldaek** [comment]
> Out of curiosity, what issues did you speak of before? Excuse me, I'm just cuirous. I've put a lot of thoughts to designing it, and I was under the imoresion it would suit everybody. Could you give me some advice as to why exactly did you decide not to go with it? You mentioned project and security requirements? It would help me make it better, if not for you, at least for others?

I wasn't referring to specific issues with your library. It's just that if I depend on something I need to be able to trust it or review the code, and I don't feel like your library is in a position right now where I can blindly trust it going forward (not enough users, and I don't know you either), and I don't see enough value in reviewing the whole code if I have a version that works for me now in composer/pcre. 

So I don't think you can do much to improve here, it's just as I explained a function of Composer being a bit of a weird citizen in the PHP world.

**Comment by Danon** [comment]
> I wasn't referring to specific issues with your library. It's just that if I depend on something I need to be able to trust it or review the code, and I don't feel like your library is in a position right now where I can blindly trust it going forward (not enough users, and I don't know you either), and I don't see enough value in reviewing the whole code if I have a version that works for me now in composer/pcre.

Yea, sure, that's very reasonable of you :) 

I've written a blog post in t-regx.com website, so that if anyone needs API for PHP 5.3, they could use `comooser/pcre`. I will deploy it today. I will also link your project. 

If you have any questions about PCRE feel free to ask me, I'm always kin to help. 

I understand why you want to use `composer/pcre` in your projects. But maybe you could use T-Regx as an internal implementstion of `composer/pcre`? As to the values, well, your current implementation can't now react to malformed patterns, which is the most common cause of errors in regular expressions, and I can imagine certain cases when you can get a fatal error. 

I will ping you when I deploy the blog post. 

For now, Best of luck in your project! I'm glad we had a discussion, I'm open for your questions if you need help with pcre; I hope we can end this issue in a good atmosphere, I'm sure you're a great developer! Thanks! Hope we can be friends.
